name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: self-hosted

    steps:
      - name: Execute Deployment Commands
        run: |
          cd /home/andri/webusb
          git pull origin main
          php8.3 /usr/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs
          php8.3 artisan migrate --force
          php8.3 artisan optimize:clear
